version: '3.1'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  php:
    build: .
    depends_on: 
      - composer
    ports:
        - 8888:8888
    volumes:
      - .:/app/
  
  composer:
    image: composer:latest
    command: install
    environment:
      - SSH_AUTH_SOCK:/ssh-auth.sock
    volumes:
      - .:/app/
      - ${SSH_AUTH_SOCK}:/ssh-auth.sock
  
  grafana:
    image: grafana/grafana:latest
    ports:
        - 3000:3000
